### ISSUE TITLE
[Bug] - Wrong unit on speed

### ISSUE THREAD

**Issue by mazipan** [jefrydco/jefrydco#121]
![Screenshot_20210213-101933_Chrome](https://user-images.githubusercontent.com/7221389/107840406-1445f700-6de5-11eb-86dd-7ac3670fe81d.jpg)

Almost all value are in `ms`. If you use `second` as a unit then you need to add `(value / 1000).toFixed(2)`, even if you show in `ms` you need to make sure the comma precision is on the same setup, adding `toFixed` become mandatory from my suggestion.

Also for CLS, it didn't have units, but it's better to show using fixed precision. I prefer to add `(cls).toFixed(2)` or you can customize the precision as you want.

**Comment by jefrydco** [comment]
Actually I look upon your Blog Mas @irfan-maulana-tkp , it seems there is no division by `1000` there, am I overlooking something? :thinking: 
![jefrydco](https://user-images.githubusercontent.com/20434351/107848841-5133dd00-6e29-11eb-81fe-4b8e3fc6aeca.png)

**Comment by jefrydco** [comment]
Btw I just realized why you add padding as a wrapper. It turns out if it opened on mobile there is no padding. :sweat_smile:

**Comment by mazipan** [comment]
In my blog, I am not state that the unit is `second`.
I prefer to show in `ms` for better precision.

In your case, you add `s` as the unit. So the unit and value is not match.

Just be aware about the value and the unit, it should be match.

`832 s` is not correct.
`832 ms` is the correct one.
Or `0.83 s` if you prefer using second

cc @jefrydco
